services:
  db:
    image: mariadb:10.6
    container_name: crypto_db
    restart: always
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: crypto_data
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - crypto_net

  
  phpmyadmin:
    image: phpmyadmin
    container_name: crypto_gui
    restart: always
    depends_on:
      - db 
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - crypto_net

networks:
  crypto_net:
    driver: bridge